"""原创固定关卡；逆向添加构造，求解器验证。"""

LEVELS = [{'name': '初识方向', 'difficulty': 'normal',
  'description': '先找朝向边界的箭头，逐步打开通路。',
  'board': [[None, 'D', None, 'R'],
            ['L', None, 'U', None],
            ['L', 'L', 'U', 'U'],
            [None, None, 'D', 'U']]},
 {'name': '交错路径', 'difficulty': 'normal',
  'description': '空格不代表畅通，留意整行与整列。',
  'board': [['L', None, 'U', 'L', None],
            ['L', 'R', None, None, None],
            ['D', None, 'D', 'U', 'R'],
            ['L', 'U', 'D', 'D', 'U'],
            ['D', 'D', 'D', 'L', 'U']]},
 {'name': '层层解锁', 'difficulty': 'normal',
  'description': '从外围开始观察，让阻挡逐层消失。',
  'board': [['L', 'R', 'U', 'U', 'R', 'R'],
            ['U', 'U', 'U', None, 'U', 'U'],
            ['L', 'D', 'R', 'D', None, 'R'],
            ['L', None, 'L', 'D', None, 'L'],
            ['D', 'D', 'R', None, None, 'R'],
            ['L', 'L', 'R', 'D', 'D', 'D']]},
 {'name': '纵横迷阵', 'difficulty': 'hard',
  'description': '同向箭头连续成墙，必须交替拆解纵横阻挡。',
  'board': [['L', 'U', 'U', 'U', 'U', 'U', 'R'],
            ['U', None, 'U', 'U', None, 'R', 'R'],
            ['L', None, 'L', 'D', None, 'D', 'R'],
            ['L', 'D', None, None, 'L', None, 'R'],
            ['D', 'D', 'D', 'D', 'R', 'R', 'R'],
            ['L', 'D', 'L', None, None, 'L', 'D'],
            ['L', 'D', 'D', 'L', 'D', 'D', 'D']]},
 {'name': '极限交织', 'difficulty': 'expert',
  'description': '大棋盘多层交叉依赖，寻找唯一的连续突破口。',
  'board': [['L', 'U', 'U', 'U', 'U', 'U', 'L', 'U'],
            ['L', 'L', None, 'L', 'U', None, None, 'R'],
            ['L', 'L', 'U', 'L', 'R', None, 'D', 'R'],
            ['L', 'L', None, 'R', None, 'R', None, 'R'],
            ['L', None, 'U', None, 'R', 'R', None, 'R'],
            ['L', 'L', 'L', 'L', 'L', 'U', None, 'U'],
            ['U', 'L', None, 'D', 'R', None, 'D', 'R'],
            ['U', 'D', 'D', 'D', 'D', 'R', 'D', 'D']]},
]
